import React from 'react'
import './Content.css'

const Content = () => {
  return (
    <div id='content'>
        <div className='items1'><h3 className='heading'><u>Items</u></h3>
            <div className='img'><img height={150} width={150} src="https://rukminim1.flixcart.com/image/150/150/kthjy4w0/water-purifier/e/u/s/ace-plus-kent-original-imag6tz43kut2rvh.jpeg?q=70" alt="" /><div className='imgName'>Kent Ro</div><center><a href="https://www.flipkart.com/search?q=ro&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off"><button className='btn1'>Shop Now</button></a></center></div>
            <div className='img'><img height={150} width={150} src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUveSaOlSaGz16MPgY-uD5uR7ix9imFQf-vg&usqp=CAU" alt="" /><div className='imgName'>Neon Camera</div><center><a href="https://www.flipkart.com/search?q=camera&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off"><button className='btn1'>Shop Now</button></a></center></div>
            <div className='img'><img height={150} width={150} src="https://rukminim1.flixcart.com/image/200/200/l5ld8y80/monitor/l/k/s/-original-imagg897ufhyvwqq.jpeg?q=70" alt="" /><div className='imgName'>Samsung Tv</div><center><a href="https://www.flipkart.com/search?q=tv%20&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off"><button className='btn1'>Shop Now</button></a></center></div>
            <div className='img'><img height={150} width={150} src="https://rukminim1.flixcart.com/image/150/150/kc29n680/otg-new/f/5/c/quick-chef-10bk-inalsa-10-original-imaft9sehjdhjfzj.jpeg?q=70" alt="" /><div className='imgName'>Micro Wave</div><center><a href="https://www.flipkart.com/search?q=microwave+oven&sid=j9e%2Cm38%2Co49&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_1_9_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_1_9_na_na_na&as-pos=1&as-type=RECENT&suggestionId=microwave+oven%7CMicrowave+Ovens&requestId=3bd9b92e-78b5-4288-8456-e6635e45c45c&as-backfill=on"><button className='btn1'>Shop Now</button></a></center></div>
            <div className='img'><img height={150} width={150} src="https://rukminim1.flixcart.com/image/150/150/kqzj7gw0/washing-machine-new/k/t/a/7-p7020ngay-lg-original-imag4vnghhh5qzhq.jpeg?q=70" alt="" /><div className='imgName'>Washing Machine</div><center><a href="https://www.flipkart.com/search?q=washing+machines&sid=j9e%2Cabm%2C8qx&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_1_6_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_1_6_na_na_na&as-pos=1&as-type=RECENT&suggestionId=washing+machines%7CWashing+Machines&requestId=61ffebeb-e44f-445d-8716-a2d2263f3a8c&as-backfill=on"><button className='btn1'>Shop Now</button></a></center></div>
            <div className='img'><img height={150} width={150} src="https://rukminim1.flixcart.com/image/150/150/krqoknk0/sewing-machine/2/j/w/new-portable-mini-household-handheld-12-built-in-stitches-ibs-original-imag5gz9dd3z8gzq.jpeg?q=70" alt="" /><div className='imgName'>Sewing Machine</div><center><a href="https://www.flipkart.com/search?q=sewing+machine&sid=j9e%2Cabm%2C0zg&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_1_4_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_1_4_na_na_na&as-pos=1&as-type=RECENT&suggestionId=sewing+machine%7CSewing+Machines&requestId=554edc93-51d8-4aeb-b3f2-dbd30483b3b8&as-backfill=on"><button className='btn1'>Shop Now</button></a></center></div>
        </div>
        <div className='items2'><h3 className='heading'><u>Recent</u></h3>
        <div className='img'><img height={150} width={150} src="https://rukminim1.flixcart.com/image/200/200/acoustic-guitar/e/y/y/dd-380c-blk-jixing-original-imaeff94e9tczafp.jpeg?q=70" alt="" /><div className='imgName'>Guitar</div><center><a href="https://www.flipkart.com/search?q=guitar&sid=ypu%2Cujd%2C7wz&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_1_6_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_1_6_na_na_na&as-pos=1&as-type=RECENT&suggestionId=guitar%7CAcoustic+Guitars&requestId=81db5498-cb96-4b39-bbeb-f4505f0ffb82&as-backfill=on"><button className='btn1'>Shop Now</button></a></center></div>
            <div className='img'><img height={150} width={150} src="https://rukminim1.flixcart.com/image/200/200/k6mibgw0/bedsheet/3/y/b/double-bedsheet-ncs4-flat-new-click-shop-original-imaez2yhc8f5k9sy.jpeg?q=70" alt="" /><div className='imgName'>Mattress</div><center><a href="https://www.flipkart.com/search?q=mattress&sid=wwe%2Crg9%2C6t1&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_1_8_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_1_8_na_na_na&as-pos=1&as-type=RECENT&suggestionId=mattress%7CBed+Mattress&requestId=b11403a9-5652-4055-bec4-b603649d862c&as-backfill=on"><button className='btn1'>Shop Now</button></a></center></div>
            <div className='img'><img height={150} width={150} src="https://rukminim1.flixcart.com/image/200/200/kzrbiq80/body-wash/2/b/w/-original-imagbzy4zkgudzec.jpeg?q=70" alt="" /><div className='imgName'>Lotion</div><center><a href="https://www.flipkart.com/search?q=lotion&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off"><button className='btn1'>Shop Now</button></a></center></div>
            <div className='img'><img height={150} width={150} src="https://rukminim1.flixcart.com/image/200/200/xif0q/kurta/h/c/u/xxl-k95165-526-deyann-original-imafj9a9t4bqhxca-bb.jpeg?q=70" alt="" /><div className='imgName'>Kurta</div><center><a href="https://www.flipkart.com/search?q=kurta&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off"><button className='btn1'>Shop Now</button></a></center></div>
            <div className='img'><img height={150} width={150} src="https://rukminim1.flixcart.com/image/200/200/k59xci80/watch/t/p/9/premium-luxury-business-casual-trendy-water-resistant-original-imafnzmembfxdyhv.jpeg?q=70" alt="" /><div className='imgName'>Watch</div><center><a href="https://www.flipkart.com/search?q=watch+for+men&sid=r18%2Cf13&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_1_5_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_1_5_na_na_na&as-pos=1&as-type=RECENT&suggestionId=watch+for+men%7CWrist+Watches&requestId=fcfb9a27-21bd-4fb9-b246-ca4580e6b3d3&as-backfill=on"><button className='btn1'>Shop Now</button></a></center></div>
            <div className='img'><img height={150} width={150} src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8lajpg7f7H7N3dJ0vbEpoicq45m0MT4GF4g&usqp=CAU" alt="" /><div className='imgName'>Bicycle</div><center><a href="https://www.flipkart.com/search?q=bicycle&sid=abc%2Culv%2Cixt&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_1_4_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_1_4_na_na_na&as-pos=1&as-type=RECENT&suggestionId=bicycle%7CCycles&requestId=90827603-9f5f-4520-ade9-b4c807b56e5c&as-backfill=on"><button className='btn1'>Shop Now</button></a></center></div>
        </div>
    </div>
  )
}

export default Content